### ISSUE TITLE
izin tanya

### ISSUE THREAD

**Issue by aliefnangis** [aldirifai/sulfat#1]
ini saya sudah coba, tapi gagal di migrasi, jadi saya pake cara manual pindah database, dan env saya pakai default, untuk login defaultnya diisi apa ya soalnya saya isi sesuai informasi pengguna tidak bisa

**Comment by aldirifai** [comment]
coba import file sql di foler db secara manual, kemudian sesuaikan file env nya dengan konfigurasi database di local

**Comment by aldirifai** [comment]
> ini saya sudah coba, tapi gagal di migrasi, jadi saya pake cara manual pindah database, dan env saya pakai default, untuk login defaultnya diisi apa ya soalnya saya isi sesuai informasi pengguna tidak bisa


coba import file sql di foler db secara manual, kemudian sesuaikan file env nya dengan konfigurasi database di local
